gcc-source-for-nvcc: Backport gcc-source allarch sstate_pkgarch commit from openembedded-core
Seen in commit https://github.com/openembedded/openembedded-core/commit/bd04d43100df64c0d638750af664cdcde7f06411

Was getting errors like the following:

```
ERROR: gcc-source-for-nvcc-13.2.0-13.2.0-r0 do_create_spdx: Could not find a static SPDX document named static-gcc-source-for-nvcc-13.2.0
ERROR: Task (...meta-tegra/recipes-devtools/gcc-for-nvcc/gcc-source-for-nvcc_13.2.bb:do_create_spdx) failed with exit code '1'
```

Backporting this patch seemed to fix things.

Signed-off-by: Eric Meyers <eric.meyers@arthrex.com>
(cherry picked from commit ad302bbe656d590dae0704e6513b75e930f63605)